### ISSUE TITLE
Currency convertation

### ISSUE THREAD

**Issue by IamDontNoob** [licson/beefyasian-pay#15]
Hello, nice plugin, thanks.
Is there way to add currency conversion? for example customer use EURO or CAD, It would be nice to display the amount in dollars under QR code (wallet address), even if the invoice amount is in another currency

**Comment by IamDontNoob** [comment]
I found this https://github.com/licson/beefyasian-pay/pulls and added, but when i am trying to pay invoice not in USD, for example RUB, conversion not happens, i got error


RuntimeException: The default currency is not USD in /var/wwwdomain/data/www/wwwdomain/store/modules/gateways/beefyasianpay/src/App.php:129
Stack trace:
#0 /var/www/wwwdomain/data/www/wwwdomain.gg/store/modules/gateways/beefyasianpay/src/App.php(408): BeefyAsianPay\App->convertToUSD(278.49, 'RUB')
#1 /var/www/wwwdomain/data/www/wwwdomain.gg/store/modules/gateways/beefyasianpay/src/App.php(259): BeefyAsianPay\App->renderPaymentHTML(Array)
#2 /var/www/wwwdomain/data/www/wwwdomain.gg/store/modules/gateways/beefyasianpay.php(63): BeefyAsianPay\App->render(Array)
#3 [internal function]: beefyasianpay_link(Array)
#4 /var/www/wwwdomain/data/www/wwwdomain.gg/store/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('beefyasianpay_l...', Array)
#5 /var/www/wwwdomain/data/www/wwwdomain.gg/store/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call('link', Array)
#6 /var/www/wwwdomain/data/www/wwwdomain.gg/store/vendor/whmcs/whmcs-foundation/lib/Invoice.php(0): WHMCS\Module\Gateway->call('link', Array)
#7 /var/www/wwwdomain/data/www/wwwdomain.gg/store/viewinvoice.php(0): WHMCS\Invoice->getPaymentLink()
#8 {main}

but defaul currency in my WHMCS installation is USD (screenshot attached)
![usd_default](https://github.com/user-attachments/assets/9ad19039-74a2-43fc-94cd-68bd3b6a4235)

**Comment by damonto** [comment]
Unfortunately, This plugin does not support multi currencies yet.
